first
Sunkerus/java-explore-with-me pull request #4
Opened 2023-06-30 11:48 UTC by Sunkerus

2023-07-03 11:32 UTC, alexache requested changes

2023-07-03 11:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/main/event/model/Event.java
> +    private Integer confirmedRequests;
Это не нужно хранить в таблице событий, можно получать список подтвержденных заявок запросом к таблице этих реквестов

2023-07-03 11:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/main/event/repository/RequestRepository.java
> +    @Query("select r from Request r " +
Почему это тоже не сделать именованием метода? Запрос по джоин таблицам хорошо работает

2023-07-03 11:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/main/event/service/EventService.java
> +    Event getEventById(Long eventId);
Лучше сервису возвращать/получать только ДТО, чтобы не было путаницы, Модели можно запрашивать напрямую у репозитория

2023-07-03 11:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/main/event/service/RequestServiceImpl.java
> +    private final UserService userService;
Лучше работать с другими репозиториями, нежели сервисами

2023-07-03 11:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/main/event/service/RequestServiceImpl.java
> +            event.setConfirmedRequests(event.getConfirmedRequests() + 1);
Так не нужно делать

2023-07-03 11:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/main/event/service/RequestServiceImpl.java
> +        event.setConfirmedRequests(event.getConfirmedRequests() + confirmedList.size());
Это лишняя часть

2023-07-03 11:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/main/exeption/ErrorHandler.java
> +    private String toString(Exception ex) {
Приватные методы пишутся после публичных

2023-07-03 11:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/main/user/mapper/UserMapper.java
> +    public UserShortDto tUserShortDto(User user) {
опечатка?

2023-07-03 11:32 UTC, alexache commented on main-service/src/main/resources/schema.sql
> +    confirmed_requests INTEGER,
Лишнее

2023-07-03 11:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/main/event/service/EventServiceImpl.java
> +    private void validationEventDate(LocalDateTime newEventDate, LocalDateTime dateBeforeEventStart) {
Приватные методы должны быть после публичных

2023-07-03 11:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/main/event/service/EventServiceImpl.java
> +    @Override
Этот и следующий метод лишние

2023-07-03 11:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/main/event/service/EventServiceImpl.java
> +            statsService.addHit(req.getRequest());
Было бы достаточно передавать в сервис только 2 параметра - uri и ip

2023-07-03 11:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/main/event/service/EventServiceImpl.java
> +        Map<Long, Long> views;
Лучше объявлять переменные ближе к месту их использования

2023-07-03 17:53 UTC, Sunkerus commented on main-service/pom.xml
> +                <version>1.1.3</version>
Исправил

2023-07-03 19:07 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/category/controller/CategoryPublicController.java
> +            @RequestParam(defaultValue = "0") @Min(0) int from,
Исправил

2023-07-03 19:20 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/category/service/CategoryServiceImpl.java
> +        Category category = categoryRepository.getReferenceById(catId);
Исправил

2023-07-03 19:52 UTC, Sunkerus commented on main-service/src/main/resources/schema.sql
> +    confirmed_requests INTEGER,
Исправил

2023-07-03 19:58 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/service/EventServiceImpl.java
> +    private void validationEventDate(LocalDateTime newEventDate, LocalDateTime dateBeforeEventStart) {
Исправил

2023-07-03 20:16 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/service/EventServiceImpl.java
> +    @Override
Исправил

2023-07-05 11:14 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/compilation/dto/CompilationMapper.java
> +            return CompilationMapper.toDto(compilation, eventService.getEventsLikeShortDto(eventIds));
Исправил

2023-07-05 11:20 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/category/service/CategoryService.java
> +    Category getCategoryById(Long catId);
Исправил

2023-07-05 13:56 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/compilation/service/CompilationServiceImpl.java
> +    public Compilation getCompilationById(Long compId) {
Исправил, сделал метод приватным. Изначально метод создавался для уменьшения повторений в коде, при получении по id.

2023-07-05 13:57 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/controller/PrivateEventController.java
> +    @ResponseStatus(HttpStatus.OK)
Исправил

2023-07-05 13:58 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/controller/PrivateEventController.java
> +            @RequestParam(defaultValue = "0") int from,
Исправил

2023-07-05 14:33 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/service/RequestServiceImpl.java
> +        event.setConfirmedRequests(event.getConfirmedRequests() + confirmedList.size());
Исправил

2023-07-05 14:34 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/exeption/ErrorHandler.java
> +    private String toString(Exception ex) {
Исправил

2023-07-05 14:41 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/service/EventServiceImpl.java
> +            statsService.addHit(req.getRequest());
Исправил!

2023-07-05 16:08 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/service/RequestServiceImpl.java
> +            event.setConfirmedRequests(event.getConfirmedRequests() + 1);
Исправил. Заменил на метод increment/decrement внутри объекта.

2023-07-05 21:53 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/compilation/dto/CompilationMapper.java
> +            return CompilationMapper.toDto(compilation, eventService.getEventsLikeShortDto(eventIds));
Исправил

2023-07-06 09:23 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/repository/RequestRepository.java
> +    @Query("select r from Request r " +
Исправил

2023-07-06 17:03 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/repository/RequestRepository.java
> +    @Query("select r from Request r " +
Исправил

2023-07-06 17:09 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/service/EventService.java
> +    Event getEventById(Long eventId);
Исправил

2023-07-07 10:25 UTC, Sunkerus commented on main-service/pom.xml
> +                <version>1.1.3</version>
Исправил

2023-07-07 11:55 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/controller/PrivateEventController.java
> +            @RequestParam(defaultValue = "0") int from,
Исправил

2023-07-07 15:43 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/compilation/service/CompilationServiceImpl.java
> +    private final EventService eventService;
Исрпавил

2023-07-08 15:00 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/compilation/dto/CompilationMapper.java
> +            return CompilationMapper.toDto(compilation, eventService.getEventsLikeShortDto(eventIds));
Исправил!

2023-07-08 20:13 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/service/RequestServiceImpl.java
> +    private final UserService userService;
Исправил

2023-07-10 01:26 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/dto/EventRequest.java
> +    private HttpServletRequest request;
Исправил

2023-07-10 01:27 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/dto/EventRequest.java
> +    private Integer from;
Исправил

2023-07-10 01:27 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/model/Event.java
> +    private Integer confirmedRequests;
Исправил

2023-07-10 12:34 UTC, alexache requested changes

2023-07-10 12:34 UTC, alexache commented on main-service/src/main/java/ru/practicum/main/compilation/service/CompilationServiceImpl.java
> +                        requestRepository.countByEventIdAndStatus(event.getId(), RequestStatus.CONFIRMED).intValue())).collect(Collectors.toList());
Это запрос к базе данных из цикла (map по списку событий). Нужно делать иначе - делать 1 запрос к базе по списку событий

2023-07-10 12:34 UTC, alexache commented on main-service/src/main/java/ru/practicum/main/event/service/EventService.java
> +    Collection<EventShortDto> getAllEventsAsPublic(HttpServletRequest httpServletRequest, Integer from, Integer size, EventRequest req);
(опционально) хорошо бы и вовсе избавиться от HttpServletRequest и поменять это на 2 аргумента - uri и ip

2023-07-10 12:34 UTC, alexache commented on main-service/src/main/java/ru/practicum/main/event/service/EventServiceImpl.java
> +                                requestRepository.countByEventIdAndStatus(event.getId(), RequestStatus.CONFIRMED).intValue()))
Это тоже еще запрос к базе в цикле по списку событий

2023-07-10 12:47 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/category/service/CategoryService.java
> +    CategoryRepository getCategoryRepository();
Слуайно оставил, как вариант прошлой реализации неправильного метода. Он нигде не используется. 
Исправил

2023-07-10 13:49 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/service/EventService.java
> +    Collection<EventShortDto> getAllEventsAsPublic(HttpServletRequest httpServletRequest, Integer from, Integer size, EventRequest req);
Исправил

2023-07-20 19:58 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/service/EventServiceImpl.java
> +                                requestRepository.countByEventIdAndStatus(event.getId(), RequestStatus.CONFIRMED).intValue()))
Исправил

2023-07-20 19:58 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/compilation/service/CompilationServiceImpl.java
> +                        requestRepository.countByEventIdAndStatus(event.getId(), RequestStatus.CONFIRMED).intValue())).collect(Collectors.toList());
Исправил

2023-07-21 10:07 UTC, alexache approved these changes

2023-07-21 10:07 UTC, alexache commented on main-service/src/main/java/ru/practicum/main/compilation/service/CompilationServiceImpl.java
> +        for (Request request : requests) {
Мне кажется, коллектором и группировкой по айди вышло бы проще

2023-07-23 13:04 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/compilation/service/CompilationServiceImpl.java
> +        for (Request request : requests) {
Спасибо за исправления, исправлю в следующей итерации.

2023-07-23 13:05 UTC, merged