add: comments
Sunkerus/java-explore-with-me pull request #5
Opened 2023-07-25 15:03 UTC by Sunkerus

2023-07-31 16:06 UTC, alexache requested changes

2023-07-31 17:37 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/controller/CommentAdminController.java
> +    @ResponseStatus(HttpStatus.OK)
Исправил

2023-07-31 17:38 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/controller/PrivateEventController.java
> +    public CommentDto postCommentViaPrivet(
Ошибся, сейчас исправил

2023-08-02 10:44 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/controller/PrivateEventController.java
> +    public CommentDto patchCommentViaPrivet(
Добавил это как дополнительную возможность для ивентов. Решил, что через ивент контроллер будет наиболее корректно, т.к. это новое свойство эвента.

2023-08-02 10:45 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/controller/PublicEventController.java
> +    private final CommentService commentService;
Исправил

2023-08-02 10:46 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/dto/CommentDto.java
> +    private String created;
Исправил

2023-08-02 10:48 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/dto/CommentIncomeDto.java
> +public class CommentIncomeDto {
Исправил

2023-08-02 10:48 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/service/CommentServiceImpl.java
> +                    throw new NotFoundException(String.format("Comment with this id: %d cannot found", eventId));
Исправил

2023-08-02 13:26 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/service/CommentServiceImpl.java
> +        commentRepository.deleteById(commentId);
Исправлено, идентично с комментарием выше

2023-08-02 13:43 UTC, Sunkerus commented on main-service/src/main/java/ru/practicum/main/event/controller/CommentPrivateController.java
> +    }
Да ,конечно может, этот метод находится в event controller, там выполняется как получение, так и исправление комментария, относительно конкретного id

2023-08-02 18:14 UTC, alexache approved these changes

2023-08-03 12:41 UTC, merged